default:
  ssl:
    ca : '/path/to/ca'
    key : '/path/to/key'
    cert : '/path/to/crt'
production:
  ssl:
    ca: "/etc/ssl/startssl13/sub.class1.server.ca.pem"
    key: "/home/cogimix/ssl/sslcogimix/ssl_dec.key"
    cert: "/home/cogimix/ssl/sslcogimix/ssl.crt"